version: '3'

services:
  mx-template-py-fastapi-bed:
    image: kromiose/mx-template-py-fastapi-bed:latest
    ports:
      - "8090:8090"  # 容器的端口:主机的端口
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:  # 健康检查
      test: ["CMD", "curl", "-f", "http://localhost:8090/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: always # 自动重启
