name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 检出代码

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 # 设置Docker Buildx，用于多架构构建

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --push --platform linux/amd64,linux/arm64 -t kromiose/mx-template-py-fastapi-bed:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USERNAME: ${{ secrets.DEPLOY_USERNAME }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
        run: |
          sshpass -p $DEPLOY_PASSWORD ssh $DEPLOY_USERNAME@$DEPLOY_SERVER "mkdir -p /tmp/mx-deploy-tmp && rm -rf /tmp/mx-deploy-tmp/*"
          scp -r ./docker-compose.yml $DEPLOY_USERNAME@$DEPLOY_SERVER:/tmp/mx-deploy-tmp/docker-compose.yml
          sshpass -p $DEPLOY_PASSWORD ssh $DEPLOY_USERNAME@$DEPLOY_SERVER "cd /tmp/mx-deploy-tmp && docker-compose up -d"

