name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  initialize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  build:
    needs: initialize
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # 设置Docker Buildx，用于多架构构建

    - name: Build Docker Image
      run: |
        docker buildx create --use
        docker buildx inspect default --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t kromiose/mx-template-py-fastapi-bed:latest .

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push Docker Image
      run: |
        docker push kromiose/mx-template-py-fastapi-bed:latest
